### ISSUE TITLE
github.io issue

### ISSUE THREAD

**Issue by avaines** [jasonbellamy/jekyll-mermaid#7]
I added the mermaid jekyll-mermaid gem to my jekyll site. 
When I uploaded it to the github.io repository I received an email stating:

  The tag `mermaid` on line 18 in `_posts/2017-10-12-postname.md` is not a recognized Liquid tag. For 
  more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

It works locally any ideas?

**Comment by ufo2mstar** [comment]
Hey @n3rden , I am facing the same issue on my blog ([`mermaid` tag not found error](https://help.github.com/articles/page-build-failed-unknown-tag-error/)).. 
Bouncing around a couple of github support pages, landed on [this page](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) where I pinned down that the `github-pages deployment pipeline` is where the issue is coming from.   

When I add this to my gemfile locally
```ruby
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
```
I am able to recreate the same error message as `github.io` gives us
```bash
jekyll 3.6.2 | Error:  Liquid syntax error (line 23): Unknown tag 'mermaid'
  Liquid Exception: Liquid syntax error (line 23): Unknown tag 'mermaid' in path/to/local/md/file
```
I am going to investigate this further, but if @jasonbellamy or anybody else can fix this before as well, that would be great! 😄 else, if i am able to fix this, i will submit my patch here as well.
Cheers

**Comment by ufo2mstar** [comment]
UPDATE: 
Am able to get it to serve properly on my local (albeit from 12 sec generate time to 32 sec now 😞)
by adding this to my `gemfile`
```ruby
group :jekyll_plugins do
  gem 'jekyll-mermaid'
  # any other jekyll-gems
end
```
But still failing on `github`

**Comment by ufo2mstar** [comment]
FINAL UPDATE: 
Alright, @n3rden  I think I finally got it... 
Jekyll-Plugins don't work when `Github pages` generate the pages itself as stated here [in this page](https://jekyllrb.com/docs/plugins/#installing-a-plugin)

>**Plugins on GitHub Pages**
GitHub Pages is powered by Jekyll. However, all Pages sites are generated using the `--safe` option to **_disable custom plugins for security reasons_**. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.
You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

So I guess the only solution is for us to generate our sites locally `jekyll build` and then push the resultant `site` directory to the branch we want to publish. Tough luck to us!

**Comment by avaines** [comment]
Excellent work @ufo2mstar , thanks for your efforts. 

Its a pity about the outcome but its good to have an answer
